# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import matplotlib.pyplot as plt
from PyQt5 import QtCore, QtGui, QtWidgets
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(642, 465)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.bSat = QtWidgets.QPushButton(self.groupBox)
        self.bSat.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bSat.setObjectName("bSat")
        self.gridLayout_2.addWidget(self.bSat, 2, 0, 1, 1)
        self.bRun = QtWidgets.QPushButton(self.groupBox)
        self.bRun.setObjectName("bRun")
        self.gridLayout_2.addWidget(self.bRun, 2, 2, 1, 1)
        self.bTimes = QtWidgets.QPushButton(self.groupBox)
        self.bTimes.setObjectName("bTimes")
        self.gridLayout_2.addWidget(self.bTimes, 2, 1, 1, 1)
        self.visOps = QtWidgets.QComboBox(self.groupBox)
        self.visOps.setObjectName("visOps")
        self.visOps.addItem("")
        self.visOps.addItem("")
        self.visOps.addItem("")
        self.visOps.addItem("")
        self.gridLayout_2.addWidget(self.visOps, 1, 0, 1, 3)
        self.fGraph = QtWidgets.QFrame(self.groupBox)
        self.fGraph.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fGraph.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fGraph.setObjectName("fGraph")
        
        # Creating canvas inside frame to plot graphs
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fGraph)
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        self.figure = plt.figure()
        self.canvas = FigureCanvas(self.figure)
        
        self.horizontalLayout.addWidget(self.canvas)
        # End of canvas
        
        self.gridLayout_2.addWidget(self.fGraph, 0, 0, 1, 3)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 642, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Simulation"))
        self.bSat.setText(_translate("MainWindow", "New Sat"))
        self.bRun.setText(_translate("MainWindow", "Run"))
        self.bRun.setShortcut(_translate("MainWindow", "Ctrl+Return"))
        self.bTimes.setText(_translate("MainWindow", "Simulation Timer"))
        self.visOps.setItemText(0, _translate("MainWindow", "Ground Tracks"))
        self.visOps.setItemText(1, _translate("MainWindow", "Earth Vis"))
        self.visOps.setItemText(2, _translate("MainWindow", "Animation"))
        self.visOps.setItemText(3, _translate("MainWindow", "Distances"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
