# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(642, 465)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Simulation = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Simulation.setFont(font)
        self.Simulation.setAlignment(QtCore.Qt.AlignCenter)
        self.Simulation.setObjectName("Simulation")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Simulation)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.new_sat = QtWidgets.QPushButton(self.Simulation)
        self.new_sat.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.new_sat.setObjectName("new_sat")
        self.gridLayout_2.addWidget(self.new_sat, 2, 0, 1, 1)
        self.run = QtWidgets.QPushButton(self.Simulation)
        self.run.setObjectName("run")
        self.gridLayout_2.addWidget(self.run, 2, 2, 1, 1)
        self.sim_timer = QtWidgets.QPushButton(self.Simulation)
        self.sim_timer.setObjectName("sim_timer")
        self.gridLayout_2.addWidget(self.sim_timer, 2, 1, 1, 1)
        self.visOps = QtWidgets.QComboBox(self.Simulation)
        self.visOps.setObjectName("visOps")
        self.visOps.addItem("")
        self.visOps.addItem("")
        self.visOps.addItem("")
        self.visOps.addItem("")
        self.gridLayout_2.addWidget(self.visOps, 1, 0, 1, 3)
        self.fGraph = QtWidgets.QFrame(self.Simulation)
        self.fGraph.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fGraph.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fGraph.setObjectName("fGraph")
        self.gridLayout_2.addWidget(self.fGraph, 0, 0, 1, 3)
        self.gridLayout.addWidget(self.Simulation, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 642, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Simulation.setTitle(_translate("MainWindow", "Simulation"))
        self.new_sat.setText(_translate("MainWindow", "New Sat"))
        self.run.setText(_translate("MainWindow", "Run"))
        self.run.setShortcut(_translate("MainWindow", "Ctrl+Return"))
        self.sim_timer.setText(_translate("MainWindow", "Simulation Timer"))
        self.visOps.setItemText(0, _translate("MainWindow", "Ground Tracks"))
        self.visOps.setItemText(1, _translate("MainWindow", "Earth Vis"))
        self.visOps.setItemText(2, _translate("MainWindow", "Animation"))
        self.visOps.setItemText(3, _translate("MainWindow", "Distances"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
