# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(508, 375)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.simulation = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.simulation.setFont(font)
        self.simulation.setTitle("")
        self.simulation.setAlignment(QtCore.Qt.AlignCenter)
        self.simulation.setObjectName("simulation")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.simulation)
        self.gridLayout_2.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_2.setSpacing(12)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.run = QtWidgets.QPushButton(self.simulation)
        self.run.setObjectName("run")
        self.gridLayout_2.addWidget(self.run, 4, 2, 1, 1)
        self.sim_timer = QtWidgets.QPushButton(self.simulation)
        self.sim_timer.setObjectName("sim_timer")
        self.gridLayout_2.addWidget(self.sim_timer, 4, 1, 1, 1)
        self.graph_frame = QtWidgets.QFrame(self.simulation)
        self.graph_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.graph_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.graph_frame.setObjectName("graph_frame")
        self.gridLayout_2.addWidget(self.graph_frame, 2, 0, 1, 3)
        self.new_sat = QtWidgets.QPushButton(self.simulation)
        self.new_sat.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.new_sat.setObjectName("new_sat")
        self.gridLayout_2.addWidget(self.new_sat, 4, 0, 1, 1)
        self.vis_ops = QtWidgets.QComboBox(self.simulation)
        self.vis_ops.setObjectName("vis_ops")
        self.vis_ops.addItem("")
        self.vis_ops.addItem("")
        self.vis_ops.addItem("")
        self.vis_ops.addItem("")
        self.gridLayout_2.addWidget(self.vis_ops, 3, 0, 1, 3)
        self.gridLayout.addWidget(self.simulation, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 508, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.run.setText(_translate("MainWindow", "Run"))
        self.run.setShortcut(_translate("MainWindow", "Ctrl+Return"))
        self.sim_timer.setText(_translate("MainWindow", "Simulation Timer"))
        self.new_sat.setText(_translate("MainWindow", "New Sat"))
        self.vis_ops.setItemText(0, _translate("MainWindow", "Ground Tracks"))
        self.vis_ops.setItemText(1, _translate("MainWindow", "Earth Vis"))
        self.vis_ops.setItemText(2, _translate("MainWindow", "Animation"))
        self.vis_ops.setItemText(3, _translate("MainWindow", "Distances"))
        self.label.setText(_translate("MainWindow", "Simulation"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
