# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SimTimesUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(645, 381)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.times_confirm = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.times_confirm.setFont(font)
        self.times_confirm.setObjectName("times_confirm")
        self.gridLayout.addWidget(self.times_confirm, 1, 1, 1, 1)
        self.times_cancel = QtWidgets.QPushButton(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.times_cancel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.times_cancel.setFont(font)
        self.times_cancel.setObjectName("times_cancel")
        self.gridLayout.addWidget(self.times_cancel, 1, 0, 1, 1)
        self.epoch_and_duration = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.epoch_and_duration.setFont(font)
        self.epoch_and_duration.setAlignment(QtCore.Qt.AlignCenter)
        self.epoch_and_duration.setFlat(False)
        self.epoch_and_duration.setCheckable(False)
        self.epoch_and_duration.setChecked(False)
        self.epoch_and_duration.setObjectName("epoch_and_duration")
        self.formLayout = QtWidgets.QFormLayout(self.epoch_and_duration)
        self.formLayout.setObjectName("formLayout")
        self.times_epoch_label = QtWidgets.QLabel(self.epoch_and_duration)
        self.times_epoch_label.setObjectName("times_epoch_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.times_epoch_label)
        self.timestep_label = QtWidgets.QLabel(self.epoch_and_duration)
        self.timestep_label.setObjectName("timestep_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.timestep_label)
        self.duration_label = QtWidgets.QLabel(self.epoch_and_duration)
        self.duration_label.setObjectName("duration_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.duration_label)
        self.set_epoch = QtWidgets.QDateTimeEdit(self.epoch_and_duration)
        self.set_epoch.setObjectName("set_epoch")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.set_epoch)
        self.set_duration = QtWidgets.QLineEdit(self.epoch_and_duration)
        self.set_duration.setObjectName("set_duration")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.set_duration)
        self.set_timestep = QtWidgets.QLineEdit(self.epoch_and_duration)
        self.set_timestep.setObjectName("set_timestep")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.set_timestep)
        self.gridLayout.addWidget(self.epoch_and_duration, 0, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 645, 22))
        self.menubar.setObjectName("menubar")
        self.menuFunctions = QtWidgets.QMenu(self.menubar)
        self.menuFunctions.setObjectName("menuFunctions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.menuFunctions.addAction(self.actionReset)
        self.menubar.addAction(self.menuFunctions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.times_confirm.setText(_translate("MainWindow", "Confirm"))
        self.times_cancel.setText(_translate("MainWindow", "Cancel"))
        self.epoch_and_duration.setTitle(_translate("MainWindow", "Simulation Epoch and Duration"))
        self.times_epoch_label.setText(_translate("MainWindow", "Epoch"))
        self.timestep_label.setText(_translate("MainWindow", "Timestep size (s)"))
        self.duration_label.setText(_translate("MainWindow", "Simulation duration (s)"))
        self.set_epoch.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy HH:mm:ss"))
        self.menuFunctions.setTitle(_translate("MainWindow", "Functions"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
        self.actionReset.setShortcut(_translate("MainWindow", "Ctrl+R"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
